### PR TITLE
Swap two numbers without third variable

### PR DESCRIPTION
**Pull request by DefCon-018**
## Have you read the Contribution Guidelines?

Yes

## Description

Swapping two numbers without using third variable.
Language used : Python

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
#593

### CODE REVIEW

**Comment by DefCon-018** [comment]
please check pull request and suggest changes if required

**Comment by sukritishah15** [comment]
@DefCon-018 - We have some conflicts with the branch.
Can you resolve it on your end?
Thank you!

**Comment by sukritishah15** [comment]
I've done a manual merge for this PR. @DefCon-018

**Comment by sukritishah15** [comment]
https://stackoverflow.com/questions/36071272/fix-unknown-repository-of-an-opened-pr-after-deleted-the-fork

Refer this, in case you wish to know, why I did a manual merge.
Probably, you deleted the forked repo.
So, we came across this error.

**Pull request closed without merging**
