### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Arsh-ak7**
## Have you read the Contribution Guidelines?
Yess

## Description
Updated readme.md

## Checklist
- [x] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by lostgirljourney** [comment]
@Arsh-ak7 hey you're doing spam PR! Don't just deliberately do this in order to get a tee. Closing this PR & marking it as INVALID.

**Comment by Arsh-ak7** [comment]
Seriously?
You can see my first PR. For the JS quicksort.
It was a genuine commit. It was just missing a space complexity.
Don't assume things on your own.

**Comment by lostgirljourney** [comment]
@Arsh-ak7 got it my apologies, you can check I have mentioned where you went wrong in previous pr!

**Comment by Arsh-ak7** [comment]
Thanks. 
Sorry for the trouble!

**Comment by lostgirljourney** [comment]
@Arsh-ak7 I think i got it where you did mistake, in readme file of patch2 branch you updated readme & in Arsh-ak7:patch2 branch you uploaded code

https://github.com/Arsh-ak7/DS-Algo-Point/blob/patch-2/JavaScript/QuickSort.js follow the link, it'll show Error.

**Comment by Arsh-ak7** [comment]
Yeah. 
I'm very new to making changes once I've made the Pull request for the initial commit.
I'll see and do it shortly.

**Comment by lostgirljourney** [comment]
Okay & apologizes from my side again. You know the scenario so I hadn't the previous PR of yours & too mention the issue you've been assigned in description of this PR! :sweat_smile:

**Comment by Arsh-ak7** [comment]
Yeah. 
My bad..
Apologies for the trouble!

**Comment by wallacecosta** [comment]
Hi, we already understand that there was a confusion when sending your solution regarding QuickSort.  But this commit must be included in the same branch referenced in Pull Request #427 to be all right.  We appreciate your contribution and will be closing this PR and waiting for this change to be applied in PR #427.  Have a nice week!!!

**Pull request closed without merging**
