### PR TITLE
Interpolation Search in Java

### PR DESCRIPTION
**Pull request by divyanshkhatana**
## Have you read the Contribution Guidelines?

(Write your answer here.)

## Description

(Write your answer here.)

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Review by manan025 — CHANGES_REQUESTED** [review]
You have not added time and space complexity and sample input output.

**Comment by sukritishah15** [comment]
@divyanshkhatana - Please make the required changes in 3-4 hours.
As we will re-review this PR in 3-4 hours.

Else, we will have to close this PR due to management purposes.

Thank you!

**Comment by sukritishah15** [comment]
@divyanshkhatana - Please add Time and Space Complexity as well at the bottom in the code in the comment.

Please do it TODAY itself. We will re-review this PR.
Thank you!

**Comment by wallacecosta** [comment]
As this is the first time that @divyanshkhatana  is contributing, then I will resolve the conflict to close the PR.

**Comment by wallacecosta** [comment]
I realized that some rules were not followed for opening this PR as a correct description and reference of the issue that is resolving.  @divyanshkhatana  please contribute to read the rules so that everyone wins!

**Comment by wallacecosta** [comment]
Conflicts resolved!

**Pull request merged**
