### PR TITLE
Sieve of Eratosthenes in C language

### PR DESCRIPTION
**Pull request by harshit-labs**
## Have you read the Contribution Guidelines?

yes

## Description

I contribute the code for the Sieve of Eratosthenes in C language.
This is one of the best algorithms to find the prime from a particular range and also to find the prime number with O(N log N) time complexity.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
#39

### CODE REVIEW

**Comment by sukritishah15** [comment]
1. Add Issue no. it fixes in PR description.
2. Add Sample I/O, Time and Space Complexity at the bottom in a multiline comment.

**Comment by harshit-labs** [comment]
please review I commit the code and add issue no in the PR description. and add sample I/O and time complexity at the bottom.

**Comment by aditik03** [comment]
@sukritishah15 conflict

**Comment by manan025** [comment]
@harshit-labs you also need to add link to your code in C/Readme.md

**Comment by harshit-labs** [comment]
I write a link but it create conflicts .

**Comment by manan025** [comment]
Okay! I will do it for you!

**Comment by harshit-labs** [comment]
thanks @manan025 .

**Pull request merged**
