### PR TITLE
SimplecalculatorusingFunctionPointer

### PR DESCRIPTION
**Pull request by dicieous**
## Have you read the Contribution Guidelines?

yes

## Description

It's a simple C Calculator Using Function Pointers.
It's a very optimized program

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)
#692
Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Review by mananchawla2005 — CHANGES_REQUESTED** [review]
Update Readme and link the issue resolved.

**Comment by dicieous** [comment]
i've updated the readme file

**Review by dicieous — COMMENTED** [review]
I've updated the Readme

**Comment by itslinotlie** [comment]
Correct me if I'm wrong, but I think @mananchawla2005 meant that you should update the README in this PR, rather than in a separate PR (makes merging to master easier afaik). Implementing this should be very straightforwards (copy the changes from the other PR into this one) and that might help speed up the process of merging this to master.

**Comment by dicieous** [comment]
> Correct me if I'm wrong, but I think @mananchawla2005 meant that you should update the README in this PR, rather than in a separate PR (makes merging to master easier afaik). Implementing this should be very straightforwards (copy the changes from the other PR into this one) and that might help speed up the process of merging this to master.

**Comment by dicieous** [comment]
I've done the changes you requested

**Comment by itslinotlie** [comment]
@dicieous I cant seem to find the original Issue number this PR is addressing. Have you been assigned this issue / does this issue even exist?

**Comment by itslinotlie** [comment]
Closed for not meeting repo requirements.

**Pull request closed without merging**
