### PR TITLE
Minimum product subset 

### PR DESCRIPTION
**Pull request by ameycodes**
## Have you read the Contribution Guidelines?

Yes

## Description

Finding the minimum product subset from an array using Greedy algorithm  

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue #603 
<br/>

### CODE REVIEW

**Comment by sunilgknair051** [comment]
Hi, I am looking for well commented code. Please do that and get back.
Thanks.

**Comment by ameycodes** [comment]
@sunilgknair051 I have updated the code. Please check.

**Comment by sunilgknair051** [comment]
@niranjantuty , please review and revert, I will squash and merge.

**Review by niranjantuty — APPROVED** [review]
@sunilgknair051 @ameycodes Code looks perfect!

**Pull request merged**
