### PR TITLE
Added Search Repeating Element using Hashmap

### PR DESCRIPTION
**Pull request by nshattuck20**
## Have you read the Contribution Guidelines?

(Write your answer here.)

## Description
Kindly review my code for issue #83 Search Repeating elements using Map/Hashmap. This simply finds duplicate elements in a hash map and adds duplications to a reversed dictionary. I was somewhat confused as to the space complexity but the run-time should be O(1). Let me know if I need to make any changes! 
(Write your answer here.)

## Checklist
- [ yes] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #83)

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by sukritishah15** [comment]
@nshattuck20 
Please add Sample I/O in a multiline comment at the bottom of the file.
Thank you!

**Review by mrjoshi0147 — APPROVED** [review]

**Review by manan025 — CHANGES_REQUESTED** [review]
Add sample I/O.

**Review by mahimagoyalx — APPROVED** [review]

**Review by manan025 — APPROVED** [review]

**Review by mahimagoyalx — APPROVED** [review]

**Review by manan025 — APPROVED** [review]

**Comment by manan025** [comment]
@nshattuck20 Can you resolve conflicts? Everything else looks great!

**Comment by nshattuck20** [comment]
I'm confused. I am not sure how to resolve the conflicts and am hesitant to proceed. I don't want to screw up anything.

**Review by mephi007 — APPROVED** [review]

**Pull request merged**
