### PR TITLE
Nth term gp

### PR DESCRIPTION
**Pull request by mananchawla2005**
## Have you read the Contribution Guidelines?

Yes
## Description

Added code for nth term of gp in python.
## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues 
#3 

Fixes Issue 
<br/>

### CODE REVIEW

**Comment by sukritishah15** [comment]
@mananchawla2005 -  Make use of multiline comments

**Comment by mananchawla2005** [comment]
@sukritishah15 is it ok now?

**Comment by sukritishah15** [comment]
> @sukritishah15 is it ok now?

Yes. Perfect! 👍

**Comment by mananchawla2005** [comment]
Thanks 😅 @sukritishah15

**Pull request merged**
