### PR TITLE
added rat maze in cpp

### PR DESCRIPTION
**Pull request by sig5**
## Have you read the Contribution Guidelines?
Yes

## Description
The classic rat maze backtracking solution implemented in cpp.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by AmanParmar-git** [comment]
you didn't end comment , maybe because of space * / -> */

**Comment by sig5** [comment]
@AmanParmar-git  fixed

**Review by mephi007 — CHANGES_REQUESTED** [review]
Can you please modify Readme.md too ?

**Comment by sig5** [comment]
@mephi007 I updated it.

**Pull request merged**
