### PR TITLE
Add longest_length_path.java

### PR DESCRIPTION
**Pull request by mcmonojit**
Added a java program to find the longest length path in a matrix which is taken as input from user.

## Have you read the Contribution Guidelines?

> Yes.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the README.md and link to my code.

> I have completed all the conditions mentioned in the checklist.

### CODE REVIEW

**Comment by sukritishah15** [comment]
@mcmonojit - README.md file inside Java folder not updated.
Also, add space complexity, just like you added time complexity.
Let me know, once done.

**Comment by mcmonojit** [comment]
I am pretty new to these so a little guidance will be very helpfull. I don't know how to edit a previous PR.

**Comment by sukritishah15** [comment]
> I am pretty new to these so a little guidance will be very helpfull. I don't know how to edit a previous PR.

For now, you can close this PR and create a new one.
Follow the steps properly.

**Comment by mcmonojit** [comment]
Hello @sukritishah15 , I want to ask that because I had to closed this PR, will this be a problem during my hacktoberfest evaluation ?

**Pull request closed without merging**
