### PR TITLE
Updated QuickSort

### PR DESCRIPTION
**Pull request by Arsh-ak7**
## Have you read the Contribution Guidelines?

Yes

## Description

Updated QuickSort

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)
Updated space complexity
Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by sukritishah15** [comment]
@Arsh-ak7 - Please mention the issue # it fixes in the PR description.
Also, update README.md file inside JavaScript folder with the file name.

Thank you!

**Comment by Arsh-ak7** [comment]
I did update ReadMe.md and also added the fix.

**Comment by sukritishah15** [comment]
> I did update ReadMe.md and also added the fix.

@Arsh-ak7 - I can see only 1 file here. See at the top - Files Changed (1)
is written.
Also, I can't see the Issue # in PR DESCRIPTION.

Let me know if you have any doubts.

**Comment by Arsh-ak7** [comment]
Sorry for the trouble.
This PR shouldn't have been there. If you'd see there was an PR request that I had made earlier to the JS file.
So I think this PR is generated for no use. 
It'd be kind of you if you can check the same.
A PR for Creating the JS file was already made by me before.

**Comment by lostgirljourney** [comment]
@Arsh-ak7 use same branch for Quick sort file linking for readme.md.

**Comment by Arsh-ak7** [comment]
I'm not used to GitHub controls for editing.
I'll see and use the same branch.
Don't just blatantly start accusing someone.

**Comment by lostgirljourney** [comment]
@Arsh-ak7 merged 🚀

**Comment by wallacecosta** [comment]
@Arsh-ak7 Very good! I hope you contribute again with other solutions !!

**Comment by Arsh-ak7** [comment]
Anytime!
Very happy to contribute!
Can you see issue#330 ? and tell if I can contribute those too.

**Pull request merged**
