### PR TITLE
added parentheses checker python

### PR DESCRIPTION
**Pull request by SuyashGupte**
## Have you read the Contribution Guidelines?

Yes

## Description

Python code for parentheses checker problem

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
#6

### CODE REVIEW

**Comment by codewithnick** [comment]
I just wanted to ask that, the pull requests which are made before oct 1 counted in hacktoberfest?

**Comment by SuyashGupte** [comment]
> I just wanted to ask that, the pull requests which are made before oct 1 counted in hacktoberfest?

No. Pull requests between Oct 1 and Oct 31 are counted.

**Comment by lostgirljourney** [comment]
No PRs before 1st October are not counted for Hacktoberfest. Only VALID PRs
between 1st to 31st October are eligible.

**Comment by lostgirljourney** [comment]
No PRs before 1st October are counted for Hacktoberfest. Only VALID PRs
between 1st to 31st October are eligible.

**Pull request merged**
