### PR TITLE
Added Binary Search in a String

### PR DESCRIPTION
**Pull request by VarunSharma117**
Implementation of binary search to find an index of char (if present) in a string.

## Have you read the Contribution Guidelines?

Yes, I have you read the Contribution Guidelines?

## Description

Implementation of Binary Search to find a char (if present) in a String

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

### CODE REVIEW

**Comment by sunilgknair051** [comment]
Hey! @VarunSharma117 , have you been assigned this issue?

**Comment by VarunSharma117** [comment]
Okay, my bad.
It will be so kind of you if you assign it to me and accept the PR.

**Comment by sunilgknair051** [comment]
> 
> 
> Okay, my bad.
> It will be so kind of you if you assign it to me and accept the PR.

@VarunSharma117, first make sure you check the folder if they have the implementation already. If not, create an issue and get assigned and, reference the issue on this PR. I will do the needful then.
Thanks!

**Review by itslinotlie — CHANGES_REQUESTED** [review]
Besides Sunil's request for following the contribution guides, you have also forgotten to create your changes on a branch. Please create the changes on a branch and redo the PR process. Thanks. Closing this PR.

**Comment by sunilgknair051** [comment]
@itslinotlie , please have a look at #793 .

**Pull request closed without merging**
