### PR TITLE
Adding string_palindrome_check.cpp, counting_sort.cpp and collatz_sequence.cpp

### PR DESCRIPTION
**Pull request by piyushsharma220699**
## Have you read the Contribution Guidelines?

Yes

## Description

I'm not sure why it is showing this way, I already raised a PR for the N Queens Problem and GCD of Two Numbers Problem and was accepted too!
This is just for merging string_palindrome_check.cpp

## Checklist
Yes - I've read the contribution guidelines.
Yes - I've checked the issue list before deciding what to submit.
Yes - I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue #520 #515 and #618
<br/>

### CODE REVIEW

**Comment by sukritishah15** [comment]
@piyushsharma220699 - There are 5 files changed.
Only 2 files are required for an issue.
Please remove other extra files.
Thank you!

**Comment by piyushsharma220699** [comment]
Sorry for that @sukritishah15 ! I guess this will work fine now. Please let me know if any changes are required :)

**Comment by piyushsharma220699** [comment]
@sukritishah15 I've updated collatz_sequence.cpp and counting_sort.cpp too! Please let me know if any changes are required! :)

**Comment by sukritishah15** [comment]
Good work @piyushsharma220699 !

**Pull request merged**
