### PR TITLE
Stack Infix and postfix example in C++

### PR DESCRIPTION
**Pull request by Hasaber8**
## Have you read the Contribution Guidelines?

Yes

## Description

Stack Infix and postfix example in C++

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
## Related Issues (Mention Issue no. like #xxx)

None

### CODE REVIEW

**Comment by aditik03** [comment]
@Hasaber8 kindly mentioned the issue no.
and if this issue is not assigned to you then comment on that issue and claim it.
Thank you

**Comment by Hasaber8** [comment]
> @Hasaber8 kindly mentioned the issue no.
> and if this issue is not assigned to you then comment on that issue and claim it.
> Thank you

https://github.com/sukritishah15/DS-Algo-Point/issues/23#issuecomment-703313535
If you could assign it to me, it will be great!

**Comment by sukritishah15** [comment]
@Hasaber8 - The issue you have linked here was meant for simple stack implementation.
We do not have an issue for Infix to postfix so far.

Please create an issue.
We will assign the issue to you and accept the PR.

Let us know if you have any doubts.

Thank you!

**Comment by Hasaber8** [comment]
> @Hasaber8 - The issue you have linked here was meant for simple stack implementation.
> We do not have an issue for Infix to postfix so far.
> 
> Please create an issue.
> We will assign the issue to you and accept the PR.
> 
> Let us know if you have any doubts.
> 
> Thank you!

https://github.com/sukritishah15/DS-Algo-Point/issues/509
Done!

**Comment by sukritishah15** [comment]
@Hasaber8 - Please add Sample I/O, Time and Space Complexity at the bottom in a multiline comment.
Thank you!

**Comment by sukritishah15** [comment]
@Hasaber8 - Please make the requested changes.
So that we can merge this PR.
Thank you!

**Comment by Hasaber8** [comment]
> @Hasaber8 - Please make the requested changes.
> So that we can merge this PR.
> Thank you!

Sorry for the delay, I was caught up in some work, will pr by today evening

**Comment by sukritishah15** [comment]
Sure, @Hasaber8

**Comment by Hasaber8** [comment]
> Sure, @Hasaber8

Done, please review it and merge

**Pull request merged**
