### PR TITLE
C++ Value of Pi from random numbers

### PR DESCRIPTION
**Pull request by ayushpattnaik**
## Have you read the Contribution Guidelines?

Yes

## Description

Used geekforgeeks' monte carlo method to solve the problem to generate the value of pi by generating random numbers.
(https://www.geeksforgeeks.org/estimating-value-pi-using-monte-carlo/)

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Issue No.
#491

### CODE REVIEW

**Comment by ayushpattnaik** [comment]
@arnav-roy  I guess, it should be correct now.

**Comment by arnav-roy** [comment]
Your code is correct but the Time and Space complexity are not well defined as the "n" that is used in the Time and Space complexity isn't defined.

**Comment by ayushpattnaik** [comment]
Is it correct now?

**Comment by arnav-roy** [comment]
Good. Now you have reported the complexity in terms of variables used. 
Can you please give an argument for why the space complexity is O(INTERVAL)? 
I think it is O(1) because the space used is independent of INTERVAL rather constant.

**Comment by ayushpattnaik** [comment]
Yes, you are correct. The rand_x and rand_y values are only being reinitialized in for loop.

**Pull request merged**
