### PR TITLE
Added Merge Sort Program using C programming language.

### PR DESCRIPTION
**Pull request by MannanAhmad**
## Have you read the Contribution Guidelines?

Yes, I read all the contribution guidelines.

## Description

Added Merge Sort program using the C programming language with very neat and clean code by using comments so that anyone can understand each and every line of my code. Also added output with time and space complexity as mentioned by you.

## Checklist
- [✔ ] I've read the contribution guidelines.
- [ ✔] I've checked the issue list before deciding what to submit.
- [✔ ] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like ##)

Implement Merge Sort issue no. :  #5

Fixes Issue: Added Merge sort program using the C programming language.
<br/>

### CODE REVIEW

**Comment by sukritishah15** [comment]
README.md file in C folder is not updated. Please update that.

**Comment by sukritishah15** [comment]
I'll re-review the PR in 2-3 hours. Kindly make the changes by then, else I'll close this PR.

**Comment by MannanAhmad** [comment]
Sure I am going to update right now

**Comment by MannanAhmad** [comment]
Updated the README.md file.
Thank You.

**Pull request merged**
