### PR TITLE
Algure BODMAS

### LINKED ISSUE #337: BODMAS Evaluator
## 🚀 

An algorithm to evaluate elaborate arithmetic equations while observing the rules of BODMAS and accounts for common mathematical syntax and operators.

### Have you read the Contribution Guidelines?

Yes

## Pitch

It can be used in all sorts of algorithms. Its like having a scientific calculator to compute any mathematical expression in your program so you just input evan a complex expression and it gives the output; e.g evaluating an expression by =>gunnercal("2+3(sin30+cos(35+5^2))") gives "5" as output.

## Assignees
@Algure - Java

### PR DESCRIPTION
**Pull request by Algure**
## Have you read the Contribution Guidelines?

YES

## Description

This class solves any arithmetic equation with the function "gunnercal" and observes the rules of BODMAS while doing so.
Logarithmic and trigonometric functions can also be evaluated with the following key phrases as input: 
NOTE: ALGORITHM IS CASE SENSITIVE

-Alog: Antilog e.g Alog0.1=Alog(0.1)=1.25

-Asin: ArcSine e.g Asin0.5=Asin(0.5)=30

-Acos: ArcCosine e.g Acos(0.5)=Acos(0.5)=60

-Atan: ArcTangent e.g Atan1= Atan(1)=45

-ln: Natural Logarithe.g ln1=ln(1)=0

-log: logarithm e.g log10=log(10)=1

-sin: Sine e.g sin30=sin(30)=0.5

-cos: Cosine e.g cos60=cos(60)=0.5

-tan: Tangent e.g tan45=tan(45)=1

-e: exponential e.g e5=e(5)=148.4

-!: factorial e.g 6!=720

-^: power e.g 2^3=8 2^-1=0.5

-Regular arithmetic:+,-,*,/,(,)etc.

Sample input: gunnercal("2+3(cos(35+5^2)+log10)")
Sample output: "6.5"

Space complexity: O(n)=>linear
Time complexity:O(n)=>linear 

## Checklist
- [ Y] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

this commit fixes #337 
<br/>
(Write your answer above.)

### CODE REVIEW

**Review by lostgirljourney — CHANGES_REQUESTED** [review]
Please add Sample I/O and SPACE & TIME Complexities. Otherwise everything alright! :smile:

**Comment by Algure** [comment]
The code is really long... Space and time complexities are included in a comment in the main method along with sample input. 
Where else do you need sample input?

**Comment by lostgirljourney** [comment]
@Algure that's okay but according to guidelines you've to make multiline comments to add Sample I/O and SPACE & TIME Complexities. I hope you follow whatever is instructed! 🕊️

**Comment by Algure** [comment]
Yes, I followed all the instructions

**Review by lostgirljourney — APPROVED** [review]

**Pull request merged**
