### PR TITLE
Nth term ap

### PR DESCRIPTION
**Pull request by mananchawla2005**
## Have you read the Contribution Guidelines?

Yes
## Description

Added code for java and python for finding nth term of ap.
## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues 
#2 
Fixes Issue 
<br/>

### CODE REVIEW

**Comment by sukritishah15** [comment]
@mananchawla2005 - Please make use of multiline comments.
And also update Python - README.md

**Comment by mananchawla2005** [comment]
I updated the readme ?  @sukritishah15

**Comment by sukritishah15** [comment]
> I updated the readme ? @sukritishah15

But, see at the top, you'll see 3 files changed. Instead of 4.
You were assigned in Java and Python.
2 files will be there for each.

Let me know if I am wrong or if there are any issues. 👍

**Comment by mananchawla2005** [comment]
@sukritishah15 now is it ok?

**Comment by sukritishah15** [comment]
Yes. @mananchawla2005 Merged.
Good work! 💯

**Comment by mananchawla2005** [comment]
Thanks alot @sukritishah15 It was my first time contributing. Had fun 😃

**Comment by sukritishah15** [comment]
> Thanks alot @sukritishah15 It was my first time contributing. Had fun 😃

Oh! Congratulations!!! Keep up the good work! All the best.

**Pull request merged**
