### PR TITLE
KMP Algorithm in Python

### PR DESCRIPTION
**Pull request by Manognya1000**
## Have you read the Contribution Guidelines?

Yes

## Description

(Write your answer here.)

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #284 )

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Review by manan025 — CHANGES_REQUESTED** [review]
Add link to your code in Python/README.md, everything else is fine! :)

**Comment by manan025** [comment]
@Manognya1000 please add link to your code in Python/README.md!

**Comment by Manognya1000** [comment]
@manan025 I've updated the README.md file.Please review it.

**Comment by manan025** [comment]
> 
> 
> @manan025 I've updated the README.md file.Please review it.

I can't see it in the PR!

**Comment by Manognya1000** [comment]
@manan025 Please review #288

**Review by manan025 — COMMENTED** [review]
You had to add both KMP algorithm and README.md update in one PR.

**Pull request closed without merging**
