### PR TITLE
Post order traversal

### PR DESCRIPTION
**Pull request by harshit-labs**
## Have you read the Contribution Guidelines?

Yes

## Description

postorder traversal in python.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
#266

### CODE REVIEW

**Comment by harshit-labs** [comment]
Please review the pull request @sukritishah15 it does not change the readme file because it creates conflict in the pull request.

**Comment by mephi007** [comment]
> Please review the pull request @sukritishah15 it does not change the readme file because it creates conflict in the pull request.

hey @harshit-labs, the Readme file change is mandatory, can you please try again once. I have checked, "Post Order Traversal" do not exist in the file, you should be able to add it.

**Comment by sukritishah15** [comment]
@harshit-labs - Please make changes in the README.md file.
Please make the required changes TODAY itself.
As we will re-review this PR in 3-4 hours.

Else, we will have to close this PR due to management purposes.

Thank you!

**Comment by harshit-labs** [comment]
Please review.

**Pull request merged**
