### PR TITLE
Swapped Two Numbers Without A Third Variable

### PR DESCRIPTION
**Pull request by FionaFR**
## Have you read the Contribution Guidelines?

Yes

## Description

I wrote the code in Scala and updated the Readme file

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #593

Fixes Issue 
<br/>Yes
(Write your answer above.)

### CODE REVIEW

**Comment by lostgirljourney** [comment]
@FionaFR can you mention the Issue no.

**Comment by FionaFR** [comment]
okay

**Comment by lostgirljourney** [comment]
Where's your code file @FionaFR ?

**Comment by FionaFR** [comment]
It's the one name "Add files via upload ". I am unable to rename it.

**Comment by FionaFR** [comment]
Scala/SwapTwoNumbers.scala

**Comment by lostgirljourney** [comment]
🚀 merged.

**Pull request merged**
