### PR TITLE
Added prefix sum in C

### PR DESCRIPTION
**Pull request by mavneeK**
## Have you read the Contribution Guidelines?

Yes

## Description

Added prefix sum

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue #721 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by sunilgknair051** [comment]
Please comment the code.
Thanks!

**Comment by mavneeK** [comment]
I have added time and space complexity along with input and output. Could you mention what else do I need to comment in the code

**Comment by sunilgknair051** [comment]
What do the variables mean?  What does prefix sum really mean? Make sure it is easy to understand for a beginner as well.
Thanks!

**Comment by mavneeK** [comment]
@sunilgknair051  I have made the changes. Please review and let me know. Thanks!

**Pull request merged**
