### PR TITLE
Added PnC in Cpp

### PR DESCRIPTION
**Pull request by kamalrt11**
## Have you read the Contribution Guidelines?

Yes

## Description

Added a simple recursive function for calculating No of Permutations and combinations for a given pair.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)
#397 
Fixes Issue 
<br/>
for finding a number of Permutations and Combinations of a given pair of numbers.
(Write your answer above.)

### CODE REVIEW

**Comment by niranjantuty** [comment]
@kamalrt11 @arnav-roy  ``C-Plus-Plus/Permutations_And_Combinations.exe`` file is not required

**Comment by kamalrt11** [comment]
Will Remove it.Thanks for clarifying

**Comment by niranjantuty** [comment]
@kamalrt11  It is removed now.  Thank you.

**Comment by kamalrt11** [comment]
@arnav-roy Extremely Sorry for that. Will take extra care from next time? Can you also remove one with the same name in C folder too? Iam not finding any immediate solution now. I assure you this won't happen again.

**Comment by niranjantuty** [comment]
@kamalrt11  I deleted that exe file in the C folder too.  Thanks for informing.

**Pull request merged**
