### PR TITLE
Automating readme check

### PR DESCRIPTION
**Pull request by Hitansh159**
## Have you read the Contribution Guidelines?
YES

## Description

Added arrange.py and hook for test of readme file

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
#702 
solved using python and git pre-push hook

I am also attaching the photos of output while trying with improper format and how to format. 

When you try to push readme with improper format
if their are 10 changes in file it will tell you where where issues are
if more the it will rather than bumping it all on you cmd it will ask you to run arrange .py

image

image

image

as I tried to push my repo as I forked it. It had many issues 
So I executed arrange.py file and it arranged every thing for me!!

image

after arranging you will need to commit those changes
After that just do normal push and taddaaa!! 
ALL README CHECK! and branch pushed!

image

### CODE REVIEW

**Comment by sunilgknair051** [comment]
@Hitansh159, this is great. I love the idea and your skillfulness. 
I am very interested to find out if we can integrate such a script into actions on the repo. Have a look, test out a action with this script and comment here when you get to something.

**Comment by Hitansh159** [comment]
Actually I did it on this repo only and the results you see are of that. 

I submitted the branch for merging this contains hook configured and arrange.py script which will work as suggested 🤘.

If I have misunderstood your comment plz let me know.

**Comment by sunilgknair051** [comment]
@Hitansh159, I have squashed and merged. There was a reversion by I created by mistake, you can ignore that.
Thanks.

**Comment by Hitansh159** [comment]
Thanks 👍
It was great joy to work for this !!

**Comment by sunilgknair051** [comment]
@Hitansh159, the problem we will have is that the workflow action has to be implemented (by everyone) and we will have conflicts on every PR requested since the order has changed on the master. I would suggest that you open an issue, specify the steps and pin it, I will add the labels so that everyone can read and use it.

**Comment by Hitansh159** [comment]
please check the issue i created if you feel any detail that is important and missing please let me know 
#729

**Pull request merged**
