### PR TITLE
Vbranch

### PR DESCRIPTION
**Pull request by vaneet-hash**
## Have you read the Contribution Guidelines?

YES

## Description

Inorder Traversal of tree

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue  #264 
<br/>
(Write your answer above.)

### CODE REVIEW

**Review by mephi007 — APPROVED** [review]

**Review by manan025 — APPROVED** [review]

**Comment by vaneet-hash** [comment]
Was trying to work on other issues but they are getting merged here automatically.

**Review by mephi007 — APPROVED** [review]

**Comment by mephi007** [comment]
hey @vaneet-hash can you please remove btHeight.c file from your commit. it seems you have deleted it.

**Comment by vaneet-hash** [comment]
> hey @vaneet-hash can you please remove btHeight.c file from your commit. it seems you have deleted it.

am not able to remove. Should i close this pr and create a new

**Comment by manan025** [comment]
Yea sure @vaneet-hash Please create a new one :)

**Pull request closed without merging**
