### PR TITLE
Combo Sort

### PR DESCRIPTION
**Pull request by mayukh00**
## Have you read the Contribution Guidelines?

YES.
## Description

COMB SORT.

## Checklist
- [yes] I've read the contribution guidelines.
- [yes] I've checked the issue list before deciding what to submit.
- [yes] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)
Fixes Issue 
<br/>
#538

### CODE REVIEW

**Comment by sukritishah15** [comment]
@mayukh00 - There is a repeated file.
Please delete that.
Thank you!

**Comment by mayukh00** [comment]
The repeated file is deleted.
@sukritishah15

**Comment by sukritishah15** [comment]
@mayukh00 - Only the repeated file was to be deleted. 
README.md is also deleted.
Please add it back.

Thank you!

**Comment by mayukh00** [comment]
README.md is Added. Sorry for the disruption. @sukritishah15

**Comment by sukritishah15** [comment]
> README.md is Added. Sorry for the disruption. @sukritishah15

No worries @mayukh00 !!!
Good work!

**Pull request merged**
