### PR TITLE
Neon

### PR DESCRIPTION
**Pull request by Devansh2005**
## Have you read the Contribution Guidelines?

Yes

## Description

Made the changes

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
#24

### CODE REVIEW

**Comment by sukritishah15** [comment]
@Devansh2005 - There are 3 files here.
CircularQueue.py should not be there.
Since this PR is for Issue #24 only.

Also, this branch has conflicts. You're not working with the updated remote repository. So, I would suggest that-
1. On your Git Bash, run the command 
git pull upstream master
2. Make changes in the files.
3. Commit and push the changes from branch

To update your forked repository, we have this command
git push origin master

If you face any issue, reach out.

**Comment by Devansh2005** [comment]
I get an error running this code.
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

can you please help out with this

**Comment by sukritishah15** [comment]
> I get an error running this code.
> fatal: 'upstream' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 
> can you please help out with this


This means you have not done this, which I assumed you did.
git remote add upstream https://github.com/sukritishah15/DS-Algo-Point.git

Keep this in mind for future.
(
This step is to be done **(only first time)**, after cloning a repo i.e. after running the command
git clone https://github.com/<YourUserName>/DS-Algo-Point.git
git remote add upstream https://github.com/sukritishah15/DS-Algo-Point.git
)

**Comment by sukritishah15** [comment]
I have resolved conflicts for you and merged it.
But, please do the suggested things from next time.
Reach out, in case you have any doubts.

**Pull request merged**
