### PR TITLE
Reverse a Linked List

### PR DESCRIPTION
**Pull request by AdeshChoudhar19**
## Have you read the Contribution Guidelines?
Yes

## Description
This is an iterative solution to reverse a given linked list.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues #31 

Fixes Issue 
<br/>
#31

### CODE REVIEW

**Comment by AdeshChoudhar19** [comment]
@sukritishah15 please check the pull request and suggest changes if required.

**Comment by sukritishah15** [comment]
@AdeshChoudhar19 - There are 2 additional binary files. Please delete them.
Only 2 files should be there.
Thank you!

**Comment by AdeshChoudhar19** [comment]
Can you check again? I have sorted the README file alphabetically with changes.

**Review by niranjantuty — CHANGES_REQUESTED** [review]
@AdeshChoudhar19 - Please delete the additional two binary files.

**Comment by AdeshChoudhar19** [comment]
I'm new to open source, can you please tell me which files to remove. I'm not able to understand the issue.

**Comment by AdeshChoudhar19** [comment]
Now please check, I have made some changes in README file. Not sure about which binary files to delete. Please name them.

**Comment by niranjantuty** [comment]
@AdeshChoudhar19  Delete the following files

``C-Plus-Plus/longest_common_subseq``
``C-Plus-Plus/Permutations_And_Combinations.exe``

**Comment by AdeshChoudhar19** [comment]
Ok

**Comment by AdeshChoudhar19** [comment]
I have deleted them already.

**Comment by AdeshChoudhar19** [comment]
Actually I have removed them as a good practice in onr of the first commits only. Also changed the README file and sorted alphabetically.

**Comment by AdeshChoudhar19** [comment]
Please go through the commit once again.

**Review by niranjantuty — APPROVED** [review]
You are good to go.  But from next time please open PR from a new branch.  Read our contribution guidelines.  Refer to this [link](https://github.com/sukritishah15/DS-Algo-Point/blob/master/STEPS_FOR_PR.md)

**Comment by AdeshChoudhar19** [comment]
Ohh, I see. Sorry for the trouble, I read that but afraid of using branches, never used it before. I will try it personally, and from next time will take care.
Thank you so much for your patience.

**Pull request merged**
