### PR TITLE
Quicksort

### PR DESCRIPTION
**Pull request by codewithnick**
## Have you read the Contribution Guidelines?

(Write your answer here.)

## Description

(Write your answer here.)

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by mephi007** [comment]
Hey @codewithnick, you have changes from other branches/commits. can you please take care of them?

**Comment by codewithnick** [comment]
I am sorry di this was my first time creating a a pr ..a I messed a few things up ..please merge the pr's it should solve all problems now..I have made new pr's there are still 2 left to be merged..I'll do it better next time thanks though for letting me participate

**Comment by mephi007** [comment]
> I am sorry di this was my first time creating a a pr ..a I messed a few things up ..please merge the pr's it should solve all problems now..I have made new pr's there are still 2 left to be merged..I'll do it better next time thanks though for letting me participate


Hey @codewithnick, using Version Control, lets you not ruin the original code base. 
I would suggest to read about the steps and commands once.
This is for your learning itself. 
@sukritishah15

**Comment by sukritishah15** [comment]
Hey @codewithnick There are 4 files in this PR.
Only 2 are required.

Please do the required changes, and we will re-review the PR.
Thank you!

@mephi007

**Comment by sukritishah15** [comment]
@codewithnick - We are closing this PR for now.
You can always create a fresh PR after making the required changes.

Please reach out to us on Telegram, if we can help in any way.
Thank you!

**Pull request closed without merging**
