### PR TITLE
Happy number python

### PR DESCRIPTION
**Pull request by SufyanKhan0**
## Have you read the Contribution Guidelines?

Yes

## Description

Adds Python Program to check if a number is happy or not

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues: 
  Happy Number #795 

Fixes Issue 
<br/>

### CODE REVIEW

**Comment by SufyanKhan0** [comment]
Please get back to me at the earliest. 
Thank you.

**Comment by SufyanKhan0** [comment]
@sukritishah15 does this PR conform to your standards, if yes, please merge it into the master.
Thank you.

**Comment by sukritishah15** [comment]
Yes @SufyanKhan0 This looks perfect!
Good to commit. Merging it!

**Comment by SufyanKhan0** [comment]
@sukritishah15 Thank You very much.
This is my first merged PR. Thanks a lot.

**Comment by sukritishah15** [comment]
Congratulations on your first merged PR!

**Comment by SufyanKhan0** [comment]
Thanks again.

**Comment by SufyanKhan0** [comment]
@sukritishah15 If I delete this branch SufyanKhan0:HappyNumberPython and the previous fork that I made will this PR link still show up?

**Pull request merged**
