### PR TITLE
get height of a binary tree added

### PR DESCRIPTION
**Pull request by nikhil121101**
## Have you read the Contribution Guidelines?

Yes

## Description

getHeight method added to java/implementingBST.java along with an update in java/README.md

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by mephi007** [comment]
Hey @nikhil121101, you have raise PR for sole issues only. Please follow the contribution guidelines and raise PR again.

**Comment by nikhil121101** [comment]
sorry but I didn't quite get it could you elaborate, please?

**Comment by nikhil121101** [comment]
I hope concern is regarding creating the function to find the height of the tree in the implimentingBST.java file, I asked it in that in the issue section and was told to do so by @manan025 . do I need to create new java file with name height of binary tree?

**Comment by manan025** [comment]
@nikhil121101 The issue is that you have uploaded temporary files as well! Would recommend you not to use JetBrains IDEs instead use VSCode and the file name is okay!

**Comment by manan025** [comment]
@mephi007 can you please tell him what was the issue?

**Comment by manan025** [comment]
@nikhil121101 I think you created 2 PRs for the same issue, and in this, you are updating a previous PR. According to the guidelines, you have to create only 1 PR per issue!

**Comment by nikhil121101** [comment]
sorry but i didn't found any such contribution guidline

**Comment by nikhil121101** [comment]
@manan025

**Comment by manan025** [comment]
Okay, Wait! I will check and respond back.

**Comment by nikhil121101** [comment]
By the way i have a branch ready with implementation in a different .java file if that's the issue . I can send a PR from that ,if its ok.

**Comment by mephi007** [comment]
> sorry but I didn't quite get it could you elaborate, please?

@nikhil121101 
>> "All PRs must be made from a Branch. Create a separate branch for every Issue you are working upon and then create a PR."
This was in Contriution guidelines. I hope, this will help you understand.
+ #229  and #22  are two different issues.

**Comment by mephi007** [comment]
hey @nikhil121101 can you please follow Contribution Guidelines before raising PR.

**Comment by nikhil121101** [comment]
Basically, I forked the repo DS-Algo-Point.git and then cloned it into my desktop. then I created a new branched name 229 and made changes in that branch and send a pull request from that branch. it would be great if you can help what am I missing?

**Pull request closed without merging**
