### PR TITLE
twin prime numbers program using php

### PR DESCRIPTION
**Pull request by hansholani**
## Have you read the Contribution Guidelines?

yes

## Description

Twin prime numbers program using php

## Checklist
- [y] I've read the contribution guidelines.
- [y] I've checked the issue list before deciding what to submit.
- [y] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)
#407

### CODE REVIEW

**Comment by arnav-roy** [comment]
@hansholani 
The code works but you need to add Time and Space complexity and sample I/O at the end of the code in a multiline comment and also update the README.md inside PHP. 

Kindly read README.md for more clarifications on this.

**Comment by hansholani** [comment]
Hi @arnav-roy 
I have made some changes, please check it.
Thank you!

**Comment by arnav-roy** [comment]
Hello @hansholani. 

Everything seems fine. Kindly do these two tasks and then your Pull request will be accepted. 
1) Request for assignment on this issue.
2) Try to write code on your own as this is exact copy of https://www.geeksforgeeks.org/twin-prime-numbers/ and plagiarism is highly discouraged in the coding community and if you aren't able to write a code yourself kindly mention a disclaimer in the code(in a comment) stating from where you have taken the help.

**Comment by hansholani** [comment]
I will do what you suggested

**Comment by hansholani** [comment]
Hey I just wanted to apologize again for taking the code from the site. The
thing is I'm new to Hacktoberfest and github and my friends said that yeah
you can take it from other places. I wasn't aware. I hope you understand. I
will try to make original pull requests tomorrow.
Thank you.

**Pull request closed without merging**
