### PR TITLE
C Twin Prime numbers  and Readme updated

### PR DESCRIPTION
**Pull request by ayushpattnaik**
## Have you read the Contribution Guidelines?

Yes
## Description
Generation of twin prime numbers between a range

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Issue No.
#407

### CODE REVIEW

**Comment by ayushpattnaik** [comment]
The code which I have written here, is the time complexity O(n) or O(n^2)?

**Comment by arnav-roy** [comment]
Hi @ayushpattnaik 
It is O(n^2). 
Your code gives wrong output for 
Input:
1 42
Your Output:
Enter start: Enter end: {3, 5}
{5, 7}
{11, 13}
{17, 19}
{29, 31}
{41, 43}

Expected output:
Enter start: Enter end: {3, 5}
{5, 7}
{11, 13}
{17, 19}
{29, 31}

**Comment by ayushpattnaik** [comment]
Oh Sorry, i will remove this bug asap

**Comment by ayushpattnaik** [comment]
@arnav-roy please review the code. It's fixed.

**Comment by ayushpattnaik** [comment]
@arnav-roy please review the code as i fixed the bug
Screenshot_2020-10-05-09-44-10-002_com android chrome

**Comment by ayushpattnaik** [comment]
@arnav-roy @sukritishah15  Kindly merge the PR if there is no issue.

**Comment by arnav-roy** [comment]
Hi @ayushpattnaik 
 Now the code is correct.

**Pull request merged**
