### PR TITLE
Added SwapNumbers.c

### PR DESCRIPTION
**Pull request by LaxmiNyamagoud**
## Have you read the Contribution Guidelines?
Yes

## Description
Swap two numbers without third variable
where x=2 and y=1
After swapping : x=1, y=2

## Checklist
- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

#593

### CODE REVIEW

**Comment by sunilgknair051** [comment]
As per the issue, @LaxmiNyamagoud ,you haven't been assigned the issue in C and you wanted to do in PHP.

**Comment by LaxmiNyamagoud** [comment]
> As per the issue, @LaxmiNyamagoud ,you haven't been assigned the issue in C and you wanted to do in PHP. Could yóu please clarify?
> Thanks!

because I got a mail  as "I want to do this in C" I think this work is assigned to me in c

**Comment by sunilgknair051** [comment]
@LaxmiNyamagoud , go through the complete #593, and please comment here and clarify where you have been assigned to it in C? (Someone sent you mail?)

**Comment by LaxmiNyamagoud** [comment]
> @LaxmiNyamagoud , go through the complete #593, and please comment here and clarify where you have been assigned to it in C? (Someone sent you mail?)

sorry,it's by mistake

**Review by sunilgknair051 — COMMENTED** [review]
Not assigned.

**Pull request closed without merging**
