### PR TITLE
Go - FibonacciNumbers

### PR DESCRIPTION
**Pull request by 100mik**
## Have you read the Contribution Guidelines?

Yes

## Description

FibonacciNumbers.go finds sum of Fibonacci series up to nth term.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
Fixes Issue (GoLang) #328 
<br/>

### CODE REVIEW

**Comment by manan025** [comment]
Can you please add the issue number you have fixed?

**Comment by manan025** [comment]
Please include issue number while making PR resolving that issue :)

**Comment by 100mik** [comment]
> Please include issue number while making PR resolving that issue :)

Sorry about that fixed!

**Comment by manan025** [comment]
Please add time and space complexity of the algorithm.

**Comment by 100mik** [comment]
> Please add time and space complexity of the algorithm.

Done!

**Review by manan025 — APPROVED** [review]

**Review by mephi007 — APPROVED** [review]

**Pull request merged**
