### PR TITLE
Interpolation Search

### PR DESCRIPTION
**Pull request by Hinal-Srivastava**
_Yes. I have read the Contribution Guidelines_

**INTERPOLATION SEARCH IN PYTHON**
This algorithm is an improvement of Binary Search. Where Binary Search considers the mid-value for comparison, interpolation search goes to different locations across the list depending on the value which needs to be searched

## Checklist
- [ 👍] I've read the contribution guidelines.
- [👍 ] I've checked the issue list before deciding what to submit.
- [👍 ] I've edited the README.md and link to my code.
 
 
Mention Issue no: [296](https://github.com/sukritishah15/DS-Algo-Point/issues/269)

### CODE REVIEW

**Comment by mananchawla2005** [comment]
Everything looks good just in your code file, add (Inside a multiline comment) Sample Input and Output at the end of the file along with Time and Space Complexity. @Hinal-Srivastava

**Comment by Hinal-Srivastava** [comment]
> Everything looks good just in your code file, add (Inside a multiline comment) Sample Input and Output at the end of the file along with Time and Space Complexity. @Hinal-Srivastava

Alright👍

**Review by lostgirljourney — APPROVED** [review]

**Comment by Hinal-Srivastava** [comment]
@lostgirljourney @mananchawla2005 it would be great if you'd label this as `#hacktoberfest` :)

**Comment by mananchawla2005** [comment]
> @lostgirljourney @mananchawla2005 it would be great if you'd label this as `#hacktoberfest` :)

It is a pull request so hactoberfest accepted is already been added.

**Pull request merged**
