### PR TITLE
Cpp create largest number #149

### PR DESCRIPTION
**Pull request by tatticoder**
## Have you read the Contribution Guidelines?

Yes

## Description

This pull request adds a algorithm which will create largest possible number from given numbers

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues #149

Fixes Issue 
<br/>
Make biggest possible number algorithm added.

### CODE REVIEW

**Comment by aditik03** [comment]
@sukritishah15 conflict

**Comment by mananchawla2005** [comment]
@tatticoder still has conflicts

**Comment by tatticoder** [comment]
@mananchawla2005 I have done minimal changes 

- I fixed a typo to remove space 
- I added link to my added file
- My text editor trimmed white-spaces at end of file but i added them manually and was able to resolve 1 conflict

I am still getting conflicts and unable to resolve them. This is my first pull request and if you can help me out I would be greateful.
I wanted to fix some names which were listed out of order but I left that out.

**Comment by mephi007** [comment]
hey @tatticoder the merge conflict is in Readme.md file. Try to check for "HEAD", "=====" and ">>>>", this tells the portion of file having merge conflict. Give a try, you can do it.

**Comment by sukritishah15** [comment]
@mephi007 was right. Conflicts were in the README.md file.
Nevermind @tatticoder I have resolved them.

Thank you!

**Pull request merged**
