### PR TITLE
series

### PR DESCRIPTION
**Pull request by shub-coder**
## Have you read the Contribution Guidelines?

(Write your answer here.)

## Description

(Write your answer here.)

## Checklist
- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by aditik03** [comment]
@sukritishah15 check this

**Comment by sukritishah15** [comment]
@shub-coder 
We don't have any issue for this PR.
Create an issue, explaining what is being done.
We will assign it to you.
Also in every PR, Sample I/O, Time and Space Complexity have to be added.

All the best!

**Comment by sukritishah15** [comment]
Are you creating an issue with proper description for this PR ?
We will re-review in 2-3 hours.
Kindly let us know, else we will close this PR.

**Comment by shub-coder** [comment]
I have created a new issue in which I would Like to work on. So I am closing this PR . Sorry for the inconvenience caused.

**Pull request closed without merging**
