### PR TITLE
Implement Binary Search

### PR DESCRIPTION
**Pull request by LaxmiNyamagoud**
## Have you read the Contribution Guidelines?

Yes

## Description
Binary Search is a searching technique used to search an element in a Sorted array.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)
 Issue no.  #63

Fixes Issue 
<br/>
(Write your answer above.)

### CODE REVIEW

**Review by niranjantuty — CHANGES_REQUESTED** [review]
Only two file changes are required for this PR.  Please delete the other two files.

**Comment by LaxmiNyamagoud** [comment]
still is there any changes?

**Comment by niranjantuty** [comment]
@LaxmiNyamagoud  You have deleted the readme file completely.  Please delete only the changes you've made there.

**Review by niranjantuty — APPROVED** [review]
Good to go :)

**Comment by LaxmiNyamagoud** [comment]
Thank you so much!

**Comment by niranjantuty** [comment]
@LaxmiNyamagoud  Next time when contribute make a PR from a separate branch.

**Comment by LaxmiNyamagoud** [comment]
> @LaxmiNyamagoud Next time when you contribute make a PR from a separate branch.

ok

**Pull request merged**
