### PR TITLE
Add fibonacci sequence sum to js

### PR DESCRIPTION
**Pull request by gfmota**
Signed-off-by: Gabriel Mota <gabrielfmota134@gmail.com>

## Have you read the Contribution Guidelines?

Yes

## Description

Add fibonacci sum with linear n time complexity and spca complexity of 2

## Checklist
- [ X ] I've read the contribution guidelines.
- [ X ] I've checked the issue list before deciding what to submit.
- [ X ] I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue
<br/>
Fibonacci Numbers #328

### CODE REVIEW

**Review by mephi007 — APPROVED** [review]

**Comment by mephi007** [comment]
hey @gfmota, Can you please resolve merge conflict?

**Comment by gfmota** [comment]
@mephi007 done

**Review by manan025 — CHANGES_REQUESTED** [review]
Please add the main function. I don't think the program can run without it. Everything else is great :+1:

**Comment by AmanParmar-git** [comment]
> Please add the main function. I don't think the program can run without it. Everything else is great :+1: 

Main function in js?

**Comment by manan025** [comment]
@AmanParmar-git :man_facepalming: Oops! :joy: Sorry! :sweat_smile:

**Review by manan025 — APPROVED** [review]

**Pull request merged**
