### PR TITLE
Adding Anagrams.cpp and lowest_common_ancestor.cpp

### PR DESCRIPTION
**Pull request by piyushsharma220699**
## Have you read the Contribution Guidelines?

Yes

## Description

Added anagrams.cpp and updated README.md file

## Checklist
Yes - I've read the contribution guidelines.
Yes - I've checked the issue list before deciding what to submit.
Yes - I've edited the README.md and link to my code.
 
 
## Related Issues (Mention Issue no. like #xxx)

Fixes Issue #629 and #657  
<br/>

### CODE REVIEW

**Comment by piyushsharma220699** [comment]
Please let me know if any changes are required :)

**Comment by sunilgknair051** [comment]
Please resolve the conflict.

**Comment by piyushsharma220699** [comment]
@sunilgknair051 @itslinotlie Please let me know if I'm supposed to do something to get this pull request merged!

**Comment by sunilgknair051** [comment]
@itslinotlie , The best way to go about this would be to close this pull, @piyushsharma220699 , please work on a branch, rather than the master itself.
 I think there is a large conflict in the files. Work on a branch, re-Pull, and we will see if it has any conflicts again or not.

**Comment by piyushsharma220699** [comment]
okay okay thanks!

**Pull request closed without merging**
